'use client';
import '@/styles/index.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Layout } from '@/containers/layouts/Layout';
import mainRoutes from '@/routes';
import { ReduxProvider, ThemeRegistry } from '@/providers';
import Popups from '@/containers/Popups';
import '@/modules/translations';
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

function LayoutAuth({
    children,
    ...props
}: {
    children: React.ReactNode;
    params: {
        [key: string]: string | string[] | undefined;
    };
}) {
    const router = useRouter();
    return <Layout params={{ ...props?.params }}>{children}</Layout>;
}

export default LayoutAuth;
