'use client';
import '@/styles/index.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Layout } from '@/containers/layouts/Layout';
import mainRoutes from '@/routes';
import { ReduxProvider, ThemeRegistry } from '@/providers';
import Popups from '@/containers/Popups';
import '@/modules/translations';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

function RootLayout({
    children,
    ...props
}: {
    children: React.ReactNode;
    params: {
        [key: string]: string | string[] | undefined;
    };
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReduxProvider>
                    <ThemeRegistry options={{ key: 'mui' }}>
                        <Layout params={{ ...props?.params }}>
                            {children}
                        </Layout>
                        <Popups />
                    </ThemeRegistry>
                </ReduxProvider>
            </body>
        </html>
    );
}

export default RootLayout;
