'use client';
import '@/styles/index.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Layout } from '@/containers/layouts/Layout';
import mainRoutes from '@/routes';
import { ReduxProvider, ThemeRegistry } from '@/providers';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

function RootLayout({ children, ...props }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReduxProvider>
                    <ThemeRegistry options={{ key: 'mui' }}>
                        <Layout
                            route={mainRoutes[0]}
                            viewPort={{ isMobile: false }}
                            userIsAuth
                            location={{ search: '' }}
                        >
                            {children}
                        </Layout>
                    </ThemeRegistry>
                </ReduxProvider>
            </body>
        </html>
    );
}

export default RootLayout;
